# Generated by Django 5.2.2 on 2026-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryupload'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='stock_level_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(check=models.Q(('min_stock__gte', 0)), name='stock_level_min_stock_gte_0'),
        ),
    ]
