# Generated by Django 5.2.2 on 2026-02-23 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stocktransfer_status'),
        ('return', '0001_initial'),
        ('sales', '0003_alter_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-return_date', '-id']},
        ),
        migrations.AddField(
            model_name='return',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='return_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', 0)), name='return_tax_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(check=models.Q(('refund_amount__gte', 0)), name='return_refund_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(check=models.Q(('original_quantity__gte', 0)), name='return_item_original_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(check=models.Q(('return_quantity__gt', 0)), name='return_item_return_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='return_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(check=models.Q(('refund_amount__gte', 0)), name='return_item_refund_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(check=models.Q(('return_quantity__lte', models.F('original_quantity'))), name='return_item_qty_lte_original_qty'),
        ),
    ]
