# Generated by Django 5.2.2 on 2026-02-23 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('loyalty_points__gte', 0)), name='customer_loyalty_points_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('total_purchases__gte', 0)), name='customer_total_purchases_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.CheckConstraint(check=models.Q(('special_discount__gte', 0)), name='customer_group_special_discount_gte_0'),
        ),
    ]
