# Generated by Django 5.2.2 on 2025-06-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('decimal_places', models.IntegerField(default=2)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_start_number', models.IntegerField(default=1)),
                ('invoice_footer_text', models.TextField(blank=True, null=True)),
                ('show_tax_in_invoice', models.BooleanField(default=True)),
                ('enable_invoice_email', models.BooleanField(default=False)),
                ('allow_partial_payments', models.BooleanField(default=True)),
                ('enable_discount', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enable_round_off', models.BooleanField(default=True)),
                ('printer_type', models.CharField(default='80mm', max_length=20)),
                ('printer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('enable_auto_print', models.BooleanField(default=True)),
                ('enable_low_stock_alert', models.BooleanField(default=True)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('enable_customer_points', models.BooleanField(default=True)),
                ('points_conversion_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
