# Generated by Django 5.2.2 on 2026-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='single_main_store'),
        ),
    ]
