# Generated by Django 4.2.10 on 2026-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_single_main_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
