# Generated by Django 5.2.2 on 2025-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='grn_number',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
