# Generated by Django 5.2.2 on 2025-06-16 17:18

import suppliers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_goodsreceiptnote_grn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='receipt_date',
            field=models.DateField(default=suppliers.models.today),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(default=suppliers.models.today),
        ),
    ]
