# Generated by Django 5.2.2 on 2026-02-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocklevel_stock_level_quantity_gte_0_and_more'),
        ('stores', '0001_initial'),
        ('suppliers', '0005_supplierinvoice_supplierinvoiceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierinvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='supplierinvoiceitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='suppliers.goodsreceiptnote'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='suppliers.purchaseorder'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='stores.store'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suppliers.supplierinvoice'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='grn_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.CheckConstraint(check=models.Q(('discount_total__gte', 0)), name='grn_discount_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', 0)), name='grn_tax_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.CheckConstraint(check=models.Q(('shipping_charges__gte', 0)), name='grn_shipping_charges_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='grn_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnoteitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='grn_item_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnoteitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='grn_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnoteitem',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0)), name='grn_item_tax_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnoteitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='grn_item_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(check=models.Q(('shipping_charges__gte', 0)), name='po_shipping_charges_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='po_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', 0)), name='po_tax_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='po_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity_ordered__gte', 0)), name='po_item_qty_ordered_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__gte', 0)), name='po_item_qty_received_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='po_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0)), name='po_item_tax_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='po_item_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('credit_period__gte', 0)), name='supplier_credit_period_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('credit_limit__gte', 0)), name='supplier_credit_limit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='supplier_invoice_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_total__gte', 0)), name='supplier_invoice_discount_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', 0)), name='supplier_invoice_tax_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(check=models.Q(('shipping_charges__gte', 0)), name='supplier_invoice_shipping_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(check=models.Q(('grand_total__gte', 0)), name='supplier_invoice_grand_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='supplier_invoice_amount_paid_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='supplier_invoice_item_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='supplier_invoice_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0)), name='supplier_invoice_item_tax_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='supplier_invoice_item_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='supplier_payment_amount_gt_0'),
        ),
    ]
