# Generated by Django 5.2.2 on 2026-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_bill_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('sodexo', 'Sodexo'), ('store_credit', 'Store Credit'), ('exchange', 'Exchange')], max_length=20),
        ),
    ]
